version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: testedb
      MYSQL_ROOT_PASSWORD: 123456Pwd@
    ports:
      - 3306:3306
    volumes:
      - ./../../db/volumes/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network
    command: ["--default-authentication-plugin=mysql_native_password"]
    profiles:
      - mysql
      - db
      - all

  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 123456Pwd@
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - ./../../db/volumes/mssql:/var/opt/mssql/data
    networks:
      - mysql-compose-network
    profiles:
      - mssql
      - db
      - all
  
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456Pwd@
    ports:
      - 27017:27017
    volumes:
      - ./../../db/volumes/mongodb:/data/db
    networks:
      - mysql-compose-network
    profiles:
      - mongo
      - db
      - all

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - mysql-compose-network
    profiles:
      - mongo
      - client
      - all

volumes:
  db:

networks: 
  mysql-compose-network:
    driver: bridge