version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: testedb
      MYSQL_ROOT_PASSWORD: 123456Pwd@
    ports:
      - 3306:3306
    volumes:
      - ./../../db/volumes/mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    profiles:
      - mysql
      - db
      - all

  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 123456Pwd@
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - ./../../db/volumes/mssql:/var/opt/mssql/data
    profiles:
      - mssql
      - db
      - all
  
  mongodb:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: example
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./../../db/volumes/mongodb:/data/db
    networks:
      - compose-network-bridge
    profiles:
      - mongodb
      - db
      - all

  mongo-client:
    container_name: mongo-client
    image: mongoclient/mongoclient:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - compose-network-bridge
    depends_on:
      - mongodb
    profiles:
      - mongoclient
      - client
      - all

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: express
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      # ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/example?authSource=admin
    networks:
      - compose-network-bridge
    links:
      - mongodb
    depends_on:
      - mongodb
    profiles:
      - mongoexpress
      - client
      - all

networks: 
  compose-network-bridge:
    driver: bridge