version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: testedb
      MYSQL_ROOT_PASSWORD: 123456Pwd@
    ports:
      - 3306:3306
    volumes:
      - ./../../db/volumes/mysql:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  mssql:
    container_name: mssql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: 123456Pwd@
      MSSQL_PID: Express
    ports:
      - 1433:1433
    volumes:
      - ./../../db/volumes/mssql:/var/opt/mssql/data
  
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./../../db/volumes/mongodb:/data/db

  mongoclient:
    container_name: mongoclient
    image: mongoclient/mongoclient:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://root:root@mongo:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-256
      MONGO_DATABASE: example
      STARTUP_DELAY: 30
    depends_on:
      - mongo
    networks:
      - mongo-network

  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_BASICAUTH_USERNAME: express
  #     ME_CONFIG_BASICAUTH_PASSWORD: express
  #     ME_CONFIG_MONGODB_PORT: 27017
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: root
  #     # ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/admin?authSource=admin&authMechanism=SCRAM-SHA-256
  #   depends_on:
  #     - mongo
  #   links:
  #     - mongo
  #   networks:
  #     - mongo-network

networks: 
  mongo-network:
    driver: bridge